from pathlib import Path
import unittest
import json


ROOT = Path(__file__).resolve().parents[1]


class FrontendStaticTests(unittest.TestCase):
    def test_mobile_pwa_shell_is_present(self):
        index = (ROOT / "static" / "index.html").read_text(encoding="utf-8")
        css = (ROOT / "static" / "styles.css").read_text(encoding="utf-8")
        manifest = (ROOT / "static" / "manifest.json").read_text(encoding="utf-8")
        service_worker = (ROOT / "static" / "service-worker.js").read_text(encoding="utf-8")
        self.assertIn('name="viewport"', index)
        self.assertIn('rel="manifest"', index)
        self.assertIn('/offline-drafts.js', index)
        self.assertIn("apple-mobile-web-app-capable", index)
        self.assertIn("@media (max-width: 860px)", css)
        self.assertIn("connection.online", css)
        self.assertIn('"display"', manifest)
        self.assertIn('"icons"', manifest)
        manifest_json = json.loads(manifest)
        icon_sources = {icon["src"] for icon in manifest_json["icons"]}
        self.assertIn("/icon-192.png", icon_sources)
        self.assertIn("/icon-512.png", icon_sources)
        self.assertIn("/icon-maskable-512.png", icon_sources)
        for icon in icon_sources:
            if icon.endswith(".png"):
                self.assertTrue((ROOT / "static" / icon.lstrip("/")).exists())
        self.assertIn("clinical-data-studio", service_worker)
        self.assertIn("/offline.html", service_worker)
        self.assertIn("/offline-drafts.js", service_worker)
        self.assertIn('url.pathname.startsWith("/api/")', service_worker)
        self.assertIn("event.respondWith(fetch(request));", service_worker)

    def test_frontend_uses_new_hardening_endpoints(self):
        app_js = (ROOT / "static" / "app.js").read_text(encoding="utf-8")
        self.assertNotIn('value="admin"', app_js)
        self.assertNotIn("admin123", app_js)
        self.assertNotIn("cds_token", app_js)
        self.assertNotIn("localStorage.setItem(\"cds_token\"", app_js)
        self.assertNotIn("Authorization", app_js)
        self.assertIn('credentials: "same-origin"', app_js)
        self.assertIn("/api/csrf", app_js)
        self.assertIn("X-CSRF-Token", app_js)
        self.assertIn("renderPasswordChangeRequired", app_js)
        self.assertIn("/assist/summary", app_js)
        self.assertIn("assistDraft", app_js)
        self.assertIn("external AI is used only when explicitly enabled", app_js)
        self.assertIn("serviceWorker", app_js)
        self.assertIn("beforeinstallprompt", app_js)
        self.assertIn("CDSOfflineDrafts", app_js)
        self.assertIn("Local Drafts", app_js)
        self.assertIn("Mobile App Setup", app_js)
        self.assertIn("bottom-nav", app_js)
        self.assertIn("encrypted-backup-form", app_js)
        self.assertIn("Create Encrypted Archive", app_js)
        self.assertIn("First Run Setup", app_js)
        self.assertIn("/records/import", app_js)
        self.assertIn("/history", app_js)
        self.assertIn("/surveys", app_js)
        self.assertIn("/invitations", app_js)
        self.assertIn("/validation", app_js)
        self.assertIn("/api-tokens", app_js)
        self.assertIn("/randomization", app_js)
        self.assertIn("/odm", app_js)
        self.assertIn("/stats-package", app_js)
        self.assertIn("/validation-package", app_js)
        self.assertIn("/readiness", app_js)
        self.assertIn("readiness-score", app_js)
        self.assertIn("/audit-export", app_js)
        self.assertIn("data-revoke-token", app_js)
        self.assertIn("type=\"file\"", app_js)
        self.assertIn("case-intake", app_js)
        self.assertIn("Case Intake", app_js)
        self.assertIn("startCaseDictation", app_js)
        self.assertIn("downloadApi", app_js)
        self.assertIn("data-case-file", app_js)
        self.assertIn("Academic AI Review", app_js)
        self.assertIn("requestCaseAiReview", app_js)
        self.assertIn("Academic Workbench", app_js)
        self.assertIn("/academic", app_js)
        self.assertIn("submitAcademicCvItem", app_js)
        self.assertIn("academic_portfolio.md", app_js)

    def test_public_survey_shell_is_present(self):
        survey_html = (ROOT / "static" / "survey.html").read_text(encoding="utf-8")
        survey_js = (ROOT / "static" / "survey.js").read_text(encoding="utf-8")
        self.assertIn('name="viewport"', survey_html)
        self.assertIn('rel="manifest"', survey_html)
        self.assertIn("/api/public/surveys/", survey_js)
        self.assertIn("Consent", survey_js)
        self.assertIn("invitationToken", survey_js)
        self.assertIn("serviceWorker", survey_js)

    def test_browser_smoke_script_is_present(self):
        smoke = (ROOT / "tests" / "browser_smoke.ps1").read_text(encoding="utf-8")
        self.assertIn("Pixel 7", smoke)
        self.assertIn("Browser smoke passed", smoke)

    def test_remote_access_guidance_is_present(self):
        app_js = (ROOT / "static" / "app.js").read_text(encoding="utf-8")
        css = (ROOT / "static" / "styles.css").read_text(encoding="utf-8")
        readme = (ROOT / "README.md").read_text(encoding="utf-8")
        deployment = (ROOT / "docs" / "DEPLOYMENT.md").read_text(encoding="utf-8")
        self.assertIn("Remote Access", app_js)
        self.assertIn("remoteAccessView", app_js)
        self.assertIn("start_easy_remote.ps1", app_js)
        self.assertIn("https://*.trycloudflare.com", app_js)
        self.assertIn("VPN Overlay", app_js)
        self.assertIn("HTTPS Tunnel", app_js)
        self.assertIn("Best Free Route", app_js)
        self.assertIn("Google Drive / GitHub Pages", app_js)
        self.assertIn("metrics-grid", css)
        self.assertIn("remote-grid", css)
        self.assertIn("Private VPN overlay", readme)
        self.assertIn("docs/FREE_REMOTE_ACCESS.md", readme)
        self.assertIn("Do not use GitHub Pages or Google Drive", readme)
        self.assertIn("Remote Access Options", deployment)
        self.assertIn("Free Remote Access Setup", deployment)
        self.assertIn("GitHub Pages: useful for documentation", deployment)

    def test_remote_access_helper_script_is_present(self):
        helper = (ROOT / "remote_access.ps1").read_text(encoding="utf-8")
        self.assertIn("Get-NetIPAddress", helper)
        self.assertIn("tailscale ip -4", helper)
        self.assertIn("cloudflared tunnel --url", helper)
        self.assertIn("Oracle Always Free", helper)
        self.assertIn("Do not store the live database", helper)

    def test_easy_remote_start_script_is_present(self):
        script = (ROOT / "start_easy_remote.ps1").read_text(encoding="utf-8")
        self.assertIn("cloudflared-windows-amd64.exe", script)
        self.assertIn("trycloudflare.com", script)
        self.assertIn("Start-Process -FilePath $python", script)
        self.assertIn("tunnel --url", script)
        self.assertIn("CheckOnly", script)

    def test_free_remote_access_deployment_files_are_present(self):
        guide = (ROOT / "docs" / "FREE_REMOTE_ACCESS.md").read_text(encoding="utf-8")
        linux_service = (ROOT / "deploy" / "install_linux_service.sh").read_text(encoding="utf-8")
        tunnel_config = (ROOT / "deploy" / "cloudflared-config.example.yml").read_text(encoding="utf-8")
        self.assertIn("Easiest Free Path", guide)
        self.assertIn("start_easy_remote.ps1", guide)
        self.assertIn("Tailscale", guide)
        self.assertIn("Cloudflare Tunnel", guide)
        self.assertIn("Oracle Cloud Always Free", guide)
        self.assertIn("systemctl enable --now clinical-data-studio.service", linux_service)
        self.assertIn("ExecStart=$PYTHON_BIN $APP_DIR/server.py", linux_service)
        self.assertIn("service: http://127.0.0.1:8765", tunnel_config)


if __name__ == "__main__":
    unittest.main()
